//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elsheimy.Components.Sms.SmsMisr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elsheimy.Components.Sms.SmsMisr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sent a lot of requests at the same time , please make a delay at least 1 sec.
        /// </summary>
        internal static string SmsResponse_1200 {
            get {
                return ResourceManager.GetString("SmsResponse_1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success, Message Submitted Successfully.
        /// </summary>
        internal static string SmsResponse_1901 {
            get {
                return ResourceManager.GetString("SmsResponse_1901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL , This means that one of the parameters was not provided.
        /// </summary>
        internal static string SmsResponse_1902 {
            get {
                return ResourceManager.GetString("SmsResponse_1902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in username or password field.
        /// </summary>
        internal static string SmsResponse_1903 {
            get {
                return ResourceManager.GetString("SmsResponse_1903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in &quot;sender&quot; field.
        /// </summary>
        internal static string SmsResponse_1904 {
            get {
                return ResourceManager.GetString("SmsResponse_1904", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in &quot;mobile&quot; field.
        /// </summary>
        internal static string SmsResponse_1905 {
            get {
                return ResourceManager.GetString("SmsResponse_1905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Credit..
        /// </summary>
        internal static string SmsResponse_1906 {
            get {
                return ResourceManager.GetString("SmsResponse_1906", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server under updating.
        /// </summary>
        internal static string SmsResponse_1907 {
            get {
                return ResourceManager.GetString("SmsResponse_1907", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date &amp; Time format in “DelayUntil=” parameter.
        /// </summary>
        internal static string SmsResponse_1908 {
            get {
                return ResourceManager.GetString("SmsResponse_1908", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Message.
        /// </summary>
        internal static string SmsResponse_1909 {
            get {
                return ResourceManager.GetString("SmsResponse_1909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Language.
        /// </summary>
        internal static string SmsResponse_1910 {
            get {
                return ResourceManager.GetString("SmsResponse_1910", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is too long.
        /// </summary>
        internal static string SmsResponse_1911 {
            get {
                return ResourceManager.GetString("SmsResponse_1911", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Environment.
        /// </summary>
        internal static string SmsResponse_1912 {
            get {
                return ResourceManager.GetString("SmsResponse_1912", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL , This means that one of the parameters was not provided or wrong information.
        /// </summary>
        internal static string SmsResponse_Error {
            get {
                return ResourceManager.GetString("SmsResponse_Error", resourceCulture);
            }
        }
    }
}
